global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    scheme: https
    basic_auth:
      username: prometheus
      password: admin@123
    tls_config:
      ca_file: /etc/prometheus/node_exporter.crt
      insecure_skip_verify: true
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9323"]

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: "ec2-instances"
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        access_key: "AWS_ACCESS_KEY"
        secret_key: "AWS_ACCESS_SECRET"
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        target_label: __address__
        replacement: $1:9100
      - action: labelmap
        regex: __meta_ec2_tag_(.+)

      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type

      - source_labels: [__meta__ec2_tag_Name]
        target_label: instance

      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id

      - regex: __meta_ec2_(.*)
        action: labelmap
        replacement: ec2_$1